import rtconfig
from building import *
import os

cwd  = GetCurrentDir()
path = [cwd]
src  = Glob('*.c')

repo_root = os.path.abspath(os.path.join(cwd, '..', '..'))
shared_dir = os.path.join(repo_root, 'shared')
shared_env = os.path.join(shared_dir, 'env_shared_memory.c')
local_shared_env = os.path.join(cwd, 'env_shared_memory.c')
if os.path.exists(shared_env) and not os.path.exists(local_shared_env):
    src += [shared_env]
    path += [shared_dir]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
